version: '3.8'
services:
  json-server:
    image: node:16
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    command: >
      sh -c "
        npm install -g json-server &&
        echo '{
          \"posts\": [
            { \"id\": 1, \"title\": \"Post 1\", \"author\": \"Author 1\" },
            { \"id\": 2, \"title\": \"Post 2\", \"author\": \"Author 2\" }
          ],
          \"comments\": [
            { \"id\": 1, \"body\": \"some comment\", \"postId\": 1 },
            { \"id\": 2, \"body\": \"another comment\", \"postId\": 1 }
          ],
          \"profile\": { \"name\": \"typicode\" }
        }' > db.json &&
        json-server --watch db.json --port 3000
      "
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/posts" ]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s

  test-runner:
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
      - ./output:/app/output
      - ./reports:/app/reports
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      json-server:
        condition: service_healthy
    environment:
      - BASE_URL=http://json-server:3000
      - TEST_TYPE=regression