name: Backend Automation API Tests

permissions:
  checks: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run tests on"
        required: true
        default: "main"
        type: string
      test_type:
        description: "Test suite to run"
        required: true
        default: "regression"
        type: choice
        options:
          - smoke
          - regression
          - schema
          - posts
          - negative
          - edgecase
          - performance

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: "0 0 * * *"  # every night at midnight UTC

jobs:
  docker-api-tests:
    name: Run Docker API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set environment variables
        run: echo "TEST_TYPE=${{ github.event.inputs.test_type || 'regression' }}" >> $GITHUB_ENV

      - name: Run docker-compose
        run: docker-compose up --build --abort-on-container-exit

      - name: Generate Allure HTML report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-html

      - name: Publish JUnit Test Report to GitHub UI
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: reports/junit.xml
          check_name: Backend API Pytest Results

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-html
          path: allure-html/

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results/

      - name: Upload Output Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: output-logs
          path: output/*.log